import {
  codeGenerationToggles,
  debugToggles,
  languageToggles,
  linkerToggles,
  machineToggles,
  namedWarnings
} from "./option-descriptors.ts";
import type { TCcOptionGroupName, TCcOptions } from "./options.ts";

// every field of a group, type checking fails when one is left out
type TFieldCatalog<TGroup> = { readonly [field in keyof Required<TGroup>]: true };

// every field of a table, the tables themselves are complete
const allFields = <TField extends string>({ fields }: { fields: { readonly [field in TField]: unknown } }) => {
  return Object.fromEntries(Object.keys(fields).map((field) => {
    return [field, true];
  })) as { [field in TField]: true };
};

const groupFields: { readonly [group in TCcOptionGroupName]: TFieldCatalog<NonNullable<TCcOptions[group]>> } = {
  driver: {
    verbose: true,
    dryRun: true,
    pipe: true,
    pthread: true,
    emitLlvm: true,
    noCanonicalPrefixes: true,
    suppressUnusedArgumentWarnings: true,
    integratedAssembler: true,
    saveTemps: true,
    workingDirectory: true,
    compilationDatabaseFile: true,
    indexStorePath: true,
    toolchainPrefixes: true,
    specs: true,
    plugins: true,
    clangArguments: true,
    llvmArguments: true,
    assemblerArguments: true,
    preprocessorArguments: true,
    parameters: true,
    architectureArguments: true,
  },
  target: {
    triple: true,
    sysroot: true,
    headerSysroot: true,
    gccToolchain: true,
    resourceDirectory: true,
    architectures: true,
    appleDeploymentTarget: true,
  },
  language: {
    ...allFields({ fields: languageToggles.names }),
    standard: true,
    ansi: true,
    cxxStandardLibrary: true,
    charSignedness: true,
    environment: true,
    openmp: true,
    inputCharset: true,
    execCharset: true,
    wideExecCharset: true,
    templateDepth: true,
    constexprDepth: true,
    disabledBuiltins: true,
    moduleName: true,
    modulesCachePath: true,
    moduleMapFiles: true,
    moduleFiles: true,
    prebuiltModulePaths: true,
  },
  machine: {
    ...allFields({ fields: machineToggles.names }),
    architecture: true,
    tune: true,
    cpu: true,
    fpu: true,
    abi: true,
    codeModel: true,
    floatAbi: true,
    branchProtection: true,
    indirectBranch: true,
    functionReturn: true,
    tlsDialect: true,
    fpmath: true,
    asmDialect: true,
    stackProtectorGuard: true,
    stackProtectorGuardRegister: true,
    stackProtectorGuardOffset: true,
    preferredStackBoundary: true,
    incomingStackBoundary: true,
    regparm: true,
    smallDataThreshold: true,
    wordSize: true,
    instructionSet: true,
    endianness: true,
    floatingPoint: true,
    subsystem: true,
  },
  preprocessor: {
    macros: true,
    includeDirectories: true,
    quoteIncludeDirectories: true,
    systemIncludeDirectories: true,
    afterIncludeDirectories: true,
    frameworkDirectories: true,
    systemFrameworkDirectories: true,
    includePrefix: true,
    prefixedIncludeDirectories: true,
    prefixedBeforeIncludeDirectories: true,
    multilib: true,
    includeFiles: true,
    macroFiles: true,
    precompiledHeader: true,
    vfsOverlays: true,
    assertions: true,
    nostdinc: true,
    nostdincxx: true,
    undef: true,
    noLineMarkers: true,
    printIncludes: true,
    traditional: true,
    traditionalCpp: true,
    trigraphs: true,
    includeDump: true,
    comments: true,
    macroDump: true,
    directivesOnly: true,
    preprocessed: true,
    workingDirectory: true,
  },
  dependencies: {
    generate: true,
    includeSystemHeaderFiles: true,
    file: true,
    filename: true,
    targets: true,
    includeMissing: true,
    missingHeadersAreGenerated: true,
  },
  debug: {
    ...allFields({ fields: debugToggles.names }),
    enable: true,
    level: true,
    format: true,
    dwarfVersion: true,
    dwarfFormat: true,
    compression: true,
    lineTablesOnly: true,
    lineDirectivesOnly: true,
  },
  codeGeneration: {
    ...allFields({ fields: codeGenerationToggles.names }),
    pic: true,
    pie: true,
    visibility: true,
    tlsModel: true,
    lto: true,
    stackProtector: true,
    controlFlowProtection: true,
    trivialAutoVarInit: true,
    fpContract: true,
    fpModel: true,
    excessPrecision: true,
    zeroCallUsedRegs: true,
    patchableFunctionEntry: true,
    randomSeed: true,
    stackCheck: true,
    strictFlexArrays: true,
    alignFunctions: true,
    alignJumps: true,
    alignLoops: true,
    alignLabels: true,
    fixedRegisters: true,
  },
  instrumentation: {
    coverage: true,
    gprof: true,
    prof: true,
    profileGenerate: true,
    profileUse: true,
    profileInstrGenerate: true,
    profileInstrUse: true,
    profileUpdate: true,
    sanitizers: true,
    sanitizerRecover: true,
    sanitizerTrap: true,
    sanitizerCoverage: true,
    sanitizerIgnoreLists: true,
    sanitizerBlacklists: true,
    profileArcs: true,
    testCoverage: true,
    coverageMapping: true,
    instrumentFunctions: true,
  },
  diagnostics: {
    color: true,
    format: true,
    messageLength: true,
    maxErrors: true,
    errorLimit: true,
    serializeFile: true,
    showOption: true,
    showCaret: true,
  },
  warnings: {
    ...allFields({ fields: namedWarnings }),
    suppressAll: true,
    pedanticErrors: true,
    error: true,
    fatalErrors: true,
  },
  linker: {
    ...allFields({ fields: linkerToggles.names }),
    shared: true,
    static: true,
    staticPie: true,
    relocatable: true,
    rdynamic: true,
    strip: true,
    staticLibgcc: true,
    sharedLibgcc: true,
    staticLibstdcxx: true,
    staticLibsan: true,
    nostdlib: true,
    nostdlibxx: true,
    nodefaultlibs: true,
    nostartfiles: true,
    nolibc: true,
    dynamicLibrary: true,
    bundle: true,
    headerpadMaxInstallNames: true,
    deadStrip: true,
    flatNamespace: true,
    entryPoint: true,
    useLinker: true,
    linkerPath: true,
    runtimeLibrary: true,
    unwindLibrary: true,
    bundleLoader: true,
    installName: true,
    compatibilityVersion: true,
    currentVersion: true,
    undefinedSymbolTreatment: true,
    exportedSymbolsList: true,
    libraryDirectories: true,
    scripts: true,
    undefinedSymbols: true,
    keywords: true,
    rpaths: true,
  },
};

export {
  groupFields
};
